# Generated by Django 4.2.7 on 2025-11-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_category_inventorycategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryproduct',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
