# Generated by Django 4.2.7 on 2025-11-25 07:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0012_posproduct_is_recipe_based'),
        ('inventory', '0004_inventorycategory_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, help_text='Barcode or Stock Code', max_length=100, null=True, unique=True)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Last purchase price per unit', max_digits=10)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre'), ('pcs', 'Pieces'), ('box', 'Box')], default='pcs', max_length=10)),
                ('min_stock_level', models.DecimalField(decimal_places=3, default=5, help_text='Alert when stock goes below this level', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if this item is no longer used')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.inventorycategory')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity purchased', max_digits=10)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0, help_text='Enter the cost amount', max_digits=10)),
                ('cost_type', models.CharField(choices=[('Total', 'Total Cost'), ('Unit', 'Per Unit Cost')], default='Total', help_text='Is this amount for the Total or Per Unit?', max_length=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, help_text='Quantity used per 1 unit of Product', max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('pos_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='posapp.posproduct')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('Wastage', 'Wastage (Damaged/Expired)'), ('Theft', 'Theft'), ('Correction', 'Inventory Correction'), ('Return', 'Return to Supplier')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity to adjust (e.g. 1.5 kg)', max_digits=10)),
                ('action', models.CharField(choices=[('ADD', 'Add Stock'), ('REMOVE', 'Remove Stock')], default='REMOVE', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='product',
        ),
        migrations.DeleteModel(
            name='InventoryProduct',
        ),
        migrations.DeleteModel(
            name='StockTransaction',
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
    ]
