# Generated by Django 4.2.7 on 2025-11-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryitem_purchase_purchaseitem_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='unit_used',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre'), ('pcs', 'Pieces')], default='pcs', max_length=5),
        ),
    ]
