# Generated by Django 4.2.7 on 2025-06-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0002_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_given',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of cash given by customer', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='change_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Change amount to return to customer', max_digits=10, null=True),
        ),
    ]
