# Generated by Django 4.2.7 on 2025-06-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0003_order_cash_given_order_change_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calculate_price_per_kg',
            field=models.BooleanField(default=False, help_text='If checked, product will be sold by weight (per kg)'),
        ),
    ]
