# Generated by Django 4.2.7 on 2025-06-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0004_product_calculate_price_per_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='original_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Original quantity for tracking stock adjustments', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity - supports decimal values for weight-based products', max_digits=10),
        ),
    ]
