# Generated by Django 4.2.7 on 2025-06-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0005_alter_orderitem_original_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the delivery person', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the delivery person', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the delivery person is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Person',
                'verbose_name_plural': 'Delivery Persons',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_person',
            field=models.ForeignKey(blank=True, help_text='Delivery person assigned to the order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posapp.deliveryperson'),
        ),
    ]
