# Generated by Django 4.2.7 on 2025-06-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0006_deliveryperson_order_delivery_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='can_access_kitchen_view',
            field=models.BooleanField(default=False, help_text='Allow access to kitchen view'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_access_pos',
            field=models.BooleanField(default=True, help_text='Allow access to POS system'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_apply_discount_codes',
            field=models.BooleanField(default=False, help_text='Allow applying discount codes'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_apply_manual_discounts',
            field=models.BooleanField(default=False, help_text='Allow applying manual discounts'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_assign_delivery_orders',
            field=models.BooleanField(default=False, help_text='Allow assigning orders to delivery persons'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_cancel_orders',
            field=models.BooleanField(default=False, help_text='Allow cancelling orders'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_complete_orders',
            field=models.BooleanField(default=False, help_text='Allow marking orders as completed'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_create_orders',
            field=models.BooleanField(default=False, help_text='Allow creating new orders'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_edit_orders',
            field=models.BooleanField(default=False, help_text='Allow editing existing orders'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_end_day',
            field=models.BooleanField(default=False, help_text='Allow ending the business day'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_manage_advance_adjustments',
            field=models.BooleanField(default=False, help_text='Allow managing advance adjustments'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_manage_bill_adjustments',
            field=models.BooleanField(default=False, help_text='Allow managing bill adjustments'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_manage_business_settings',
            field=models.BooleanField(default=False, help_text='Allow editing business settings'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_manage_categories',
            field=models.BooleanField(default=False, help_text='Allow creating/editing categories'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_manage_delivery_persons',
            field=models.BooleanField(default=False, help_text='Allow managing delivery persons'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_manage_discounts',
            field=models.BooleanField(default=False, help_text='Allow creating/editing discount codes'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_manage_payments',
            field=models.BooleanField(default=False, help_text='Allow managing payment transactions'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_manage_products',
            field=models.BooleanField(default=False, help_text='Allow creating/editing products'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_manage_roles',
            field=models.BooleanField(default=False, help_text='Allow creating/editing user roles'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_manage_stock',
            field=models.BooleanField(default=False, help_text='Allow adjusting stock levels'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_manage_system_settings',
            field=models.BooleanField(default=False, help_text='Allow editing system settings'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_manage_users',
            field=models.BooleanField(default=False, help_text='Allow creating/editing users'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_print_receipts',
            field=models.BooleanField(default=True, help_text='Allow printing receipts'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_view_all_orders',
            field=models.BooleanField(default=False, help_text='Allow viewing all orders'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_view_audit_logs',
            field=models.BooleanField(default=False, help_text='Allow viewing audit logs'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_view_delivery_reports',
            field=models.BooleanField(default=False, help_text='Allow viewing delivery reports'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_view_detailed_reports',
            field=models.BooleanField(default=False, help_text='Allow viewing detailed financial reports'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_view_reports',
            field=models.BooleanField(default=False, help_text='Allow viewing sales reports'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_view_stock',
            field=models.BooleanField(default=False, help_text='Allow viewing stock levels'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_view_user_sessions',
            field=models.BooleanField(default=False, help_text='Allow viewing active user sessions'),
        ),
    ]
