# Generated by Django 4.2.7 on 2025-06-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0007_userrole_can_access_kitchen_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_apply_discount_codes',
            field=models.BooleanField(default=False, help_text='Allow applying discount codes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_apply_manual_discounts',
            field=models.BooleanField(default=False, help_text='Allow applying manual discounts'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_cancel_orders',
            field=models.BooleanField(default=False, help_text='Allow cancelling orders'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_orders',
            field=models.BooleanField(default=False, help_text='Allow editing orders'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_orders_with_password',
            field=models.BooleanField(default=False, help_text='Allow editing orders with admin password verification'),
        ),
    ]
