# Generated by Django 4.2.7 on 2025-06-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0008_userprofile_can_apply_discount_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission percentage per delivery order', max_digits=5),
        ),
    ]
