# Generated by Django 4.2.7 on 2025-11-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0009_deliveryperson_commission_percentage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='PosCategory',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='PosProduct',
        ),
    ]
