# Generated by Django 4.2.7 on 2025-11-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0010_rename_category_poscategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='posapp.poscategory'),
        ),
    ]
