# Generated by Django 4.2.7 on 2025-11-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0011_alter_posproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posproduct',
            name='is_recipe_based',
            field=models.BooleanField(default=False, help_text='Check this if product is made in kitchen using raw ingredients'),
        ),
    ]
